name: covid19_emd_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.19.0
  - scipy>=1.7.0
  - matplotlib>=3.3.0
  - pandas>=1.2.0
  - scikit-learn>=0.24.0
  - jupyter>=1.0.0
  - seaborn>=0.11.0
  - pip
  - pip:
    - PyEMD>=0.5.0 